### ISSUE TITLE
What is the installation process that I should follow?

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [anishdcruz/apex#5]
1 ) composer install
2 ) cp .env.example .env
3 ) edit .env
4 ) php artisan key:generate
5 ) php artisan migrate
6 ) php artisan db:seed
7 ) npm install

8 )  npm run hmr

C:\laragon\www\apex\webpack.config.js:126
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at requireConfig (C:\laragon\www\apex\node_modules\webpack\bin\convert-argv.js:96:18)
    at C:\laragon\www\apex\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)

How do i generate js css files

**Comment by anishdcruz** [comment]
Hi anderson,

This issue might be related to node version, try using latest 6 or 7. 

Also, this project is still in development and i not happy with code. So I will soon start from scratch.

**Comment by codebangla** [comment]
php artisan db:seed gives me error in quotation seed file, also did not find any route for register a new user.

**Comment by anishdcruz** [comment]
@codebangla there is no register at the moment. This project is a work in progress. So I will soon start from scratch with better docs.

**Comment by showketbhat** [comment]
> How do i generate js css files

Hi, Were you able to generate these app.js and app.css files, If so, Please let me know
